@startuml subnet-0axx

component outbound #LightGreen

node "0.a.0.0" as 0a00 #Yellow
node "0.a.0.1" as 0a01 #Yellow
node "0.a.0.2" as 0a02 #Yellow
node "0.a.0.3" as 0a03 #Yellow

storage r1
storage r2
storage r3
storage r4

hexagon "D(0.a.0.0)" as D_0a00
hexagon "D(0.a.0.1)" as D_0a01
hexagon "D(0.a.0.2)" as D_0a02
hexagon "D(0.a.0.3)" as D_0a03
hexagon "back_all" as back_all

outbound -- "0" r1

r1 "1" --> D_0a00
r1 "2" -- "0" r2

r2 "1" --> D_0a01
r2 "2" -- "0" r3

r3 "1" --> D_0a02
r3 "2" -- "0" r4

r4 "1" --> D_0a03
r4 "2" --> back_all

D_0a00 -- 0a00
D_0a01 -- 0a01
D_0a02 -- 0a02
D_0a03 -- 0a03

@enduml